name: memogenerator
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.3
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  google_fonts: ^2.3.2
  uuid: ^3.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
